# Generated by Django 5.1.1 on 2024-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('ano_lancamento', models.IntegerField()),
                ('duracao', models.DurationField()),
                ('genero', models.CharField(max_length=100)),
                ('classificacao_etaria', models.CharField(max_length=10)),
                ('idioma_original', models.CharField(max_length=100)),
                ('data_estreia', models.DateField()),
                ('avaliacao_media', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
            ],
        ),
    ]
